# Project metadata for humans to read
# Not used by the application at runtime

project-meta:
  project-name: Ethan's Portfolio Project
  date-started: 2025-09-27 # Approximate
  last-updated: 2026-04-16
  languages:
    - React
    - TypeScript
    - CSS
  status: Stable
  license: MIT
  version: 3.2.0

build:
  dev-environments:
    - Ubuntu (WSL2)
  test-environments:
    - Ubuntu (WSL2)
    - Mozilla Firefox
  target-platforms:
    - Cross-platform (browser)
  compiler:
    compiler-name: tsc
    compiler-version: 5.9.3

team:
  author: Ethan Kletschke
  contributors:
    - name: Ethan Kletschke
      role: Owner and Author
      github-username: ethanKletschke
